### ISSUE TITLE
Why is requirements.txt so bloated?

### ISSUE THREAD

**Issue by ekhaydarov** [deepak7376/downcast#1]
Thanks for this package.

Was just wondering why the requirements.txt has seaborn and scipy etc?

**Comment by deepak7376** [comment]
I used seaborn for plotting the graph. scipy used for different statistical test. but for now there is no need. I will update it soon.

**Comment by ekhaydarov** [comment]
Graph plotting is only an extra, I would hesitate to include that. If you would like some help contributing let me know

**Comment by deepak7376** [comment]
yes, change it according to you . I will merge it.
